name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checks
        run: pwd
      - name: Checks2
        run: bash /home/runner/work/react-class/.github/workflows/deploy.sh