name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd
      - name: LS
        run: ls
      - name: DIR
        run: dir
      - name: Checks2
        run: sh ./deploy.sh