name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: PWD
        run: pwd
      - name: LS
        run: ls
      - name: Create 1
        run: echo 'cd /home/runner/work/react-class/\nls' > ci.sh
      - name: Create 2
        run: sh ci.sh