name: Build

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run script
        run:  | 
            chmod +x ./deploy.sh
            ./deploy.sh
        shell: bash